steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/demo:$SHORT_SHA", "."]
  - id: 'Deploy to gke'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=kube-cluster'
      - 'KUBECONFIG=/.kube/config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
            gcloud container clusters get-credentials kube-cluster --project $PROJECT_ID --zone europe-west4-b
            sed -i 's|gcr.io/project-id/my-app|gcr.io/$PROJECT_ID/demo:$SHORT_SHA|' ./deployment.yaml
            kubectl apply -f ./deployment.yaml
            kubectl apply -f ./service.yaml
    timeout: 2000s
images: ["gcr.io/$PROJECT_ID/demo"]
# [END cloudbuild_maven]